### ISSUE TITLE
Does lehre support Vue?

### ISSUE THREAD

**Issue by fannheyward** [yaegassy/coc-jsdoc#1]
coc-jsdoc can replace https://github.com/fannheyward/coc-docthis

**Comment by yaegassy** [comment]
Hi, @fannheyward

coc-jsdoc is my experimental project. (WIP)

I found a few problems with the "lehre" tool itself that bothered me, so I've stopped working on it.

`coc-docthis` I'll give it a try. Thanks. 🙇
